[ozone/external_wayland] Fix dependences for build desktop_aura
Due to racing targets/dependencies in compilation,
in some cases we can get errors like
 * FAILED: obj/ozone/ui/desktop_aura/views_ozone_wayland/desktop_window_tree_host_ozone_wayland.o
   ...
   ../../ui/views/view.h:22:10: fatal error: 'ui/accessibility/ax_enums.h' file not found
   #include "ui/accessibility/ax_enums.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~